---
title: "Take-home_Ex03"
author: "Huynh Minh Phuong"
---

```{r}
pacman::p_load(jsonlite, tidygraph,ggraph,visNetwork,graphlayouts,ggforce,tidytext,tidyverse)
```

Undirected graph

```{r}
mc3_data <-fromJSON("data/MC3.json")

```

Source, target and type data is a list

```{r}
mc3_edges <-as_tibble(mc3_data$links)
glimpse(mc3_edges)
```

```{r}
mc3_edges <-mc3_edges %>% 
  distinct() %>%
  mutate(source=as.character(source),
         target=as.character(target),
         type=as.character(type)) %>% 
  group_by(source, target, type) %>% 
  summarise(weights=n()) %>% 
  filter(source!=target) %>% 
  ungroup()
  
```

```{r}
mc3_nodes <-as_tibble(mc3_data$nodes)
```

```{r}
mc3_nodes<-mc3_nodes %>% 
  mutate(country=as.character(country),
         id=as.character(id),
         product_services=as.character(product_services),
         revenue_omu=as.numeric(as.character(revenue_omu)),
         type=as.character(type)) %>% 
  select(id, country, type, revenue_omu, product_services)
```

```{r}
ggplot(mc3_nodes, aes(x=type))+
  geom_bar()
```

Possible type of relationship

owner to business

company to company

company contact to company- customer to business

or by product_service
